version: '3'
services:
  client:
    restart: always
    build:
      context: ./client
      target: prod
    env_file:
      - .env
    ports:
      - $CLIENT_PORT:3000
    depends_on:
      - server
  server:
    restart: always
    build:
      context: ./server
      target: prod
    env_file:
      - .env
    ports:
      - $SERVER_PORT:3007
    depends_on:
      - mongo
  mongo:
    image: "mongo:4.4"
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
