version: '3'
services:
  client:
    build:
      context: ./client
      target: dev
    volumes:
      - ./client/:/usr/src/app:delegated
  server:
    build:
      context: ./server
      target: dev
    volumes:
      - ./server/:/usr/src/app:delegated
